"""
Multilingual Translation Utility for Flask Skin Disease Detection App
"""

import os
from flask import session
from functools import lru_cache
from deep_translator import GoogleTranslator

class MultiLanguageTranslator:
    def __init__(self):
        self.default_lang = 'en'
        self.supported_languages = {
            'en': 'English',
            'hi': 'Hindi', 
            'mr': 'Marathi'
        }
        
        # Pre-defined translations for common UI text
        self.translations = {
            'en': {
                'skin_disease_detection': 'Skin Disease Detection',
                'login': 'Login',
                'register': 'Register',
                'dashboard': 'Dashboard',
                'contact': 'Contact',
                'chat': 'Chat',
                'upload': 'Upload',
                'about': 'About',
                'home': 'Home',
                'username': 'Username',
                'email': 'Email',
                'password': 'Password',
                'submit': 'Submit',
                'cancel': 'Cancel',
                'book_appointment': 'Book Appointment',
                'doctor': 'Doctor',
                'patient': 'Patient',
                'select_doctor': 'Select Doctor',
                'select_date': 'Select Date',
                'select_time': 'Select Time',
                'describe_issue': 'Describe your health issue',
                'welcome': 'Welcome',
                'logout': 'Logout',
                'profile': 'Profile',
                'settings': 'Settings',
                'services': 'Services',
                'diagnosis_result': 'Diagnosis Result',
                'confidence': 'Confidence',
                'risk_level': 'Risk Level',
                'symptoms': 'Symptoms',
                'prevention': 'Prevention',
                'treatment': 'Treatment',
                'upload_image': 'Upload Image',
                'choose_file': 'Choose File',
                'analyze': 'Analyze',
                'loading': 'Loading...',
                'error': 'Error',
                'success': 'Success',
                'warning': 'Warning',
                'please_wait': 'Please wait...',
                'processing': 'Processing...',
                'results_ready': 'Results Ready',
                'no_results': 'No Results Found',
                'try_again': 'Try Again',
                'appointment_booked': 'Appointment Booked Successfully!',
                'appointment_failed': 'Failed to Book Appointment',
                'invalid_credentials': 'Invalid Credentials',
                'user_exists': 'User Already Exists',
                'registration_success': 'Registration Successful!',
                'login_success': 'Login Successful!',
                'logout_success': 'Logged Out Successfully!',
                'select_language': 'Select Language',
                'english': 'English',
                'hindi': 'हिंदी',
                'marathi': 'मराठी',
                'get_started': 'Get Started',
                'ai_detection': 'AI Disease Detection',
                'home_remedies': 'Home Remedies',
                'video_consultation': 'Video Consultation',
                'appointment_booking': 'Appointment Booking',
                'hospital': 'Hospital',
                'hospitals': 'Hospitals',
                'welcome_to_snehdip_skincare_hospital': 'Welcome to Snehdip SkinCare Hospital',
                'hospitals_services_description': 'Skin treatments, dermatology, cosmetic procedures, acne treatment, laser therapy, skincare consultation.',
                'snehdip_skincare_is_dedicated_to_providing_the_best_dermatological_services_with_a_focus_on_modern_treatments_patient_comfort_and_professional_care': 'Snehdip SkinCare is dedicated to providing the best dermatological services with a focus on modern treatments, patient comfort, and professional care.',
                'online_consultation': 'Online Consultation',
                'contact_doctor': 'Contact Doctor',
                'chat_with_bot': 'Chat with AI Assistant',
                'please_log_in': 'Please log in to continue',
                'enter_email': 'Enter your email',
                'enter_password': 'Enter your password',
                'dont_have_account': "Don't have an account",
                'register_here': 'Register here',
                'create_account': 'Create your account',
                'role': 'Role',
                'select_role': 'Select Role',
                'enter_username': 'Enter username',
                'enter_name': 'Enter Name',
                'enter_email': 'Enter Email',
                'select_doctor': 'Select Doctor',
                'select_date_first': '-- Select Date First --',
                'book_appointment_description': 'Schedule your consultation with our expert dermatologists',
                'already_have_account': 'Already have an account',
                'login_here': 'Login here',
                'chat_doctor': 'Chat Doctor',
                'my_appointments': 'My Appointments',
                'upload_skin_image': 'Upload Skin Image',
                'find_hospitals': 'Find Hospitals',
                'buy_medicines': 'Buy Medicines',
                'open_records': 'Open Records',
                'my_records': 'My Records',
                'appointment_queue': 'Appointment Queue',
                'home_remedies': 'Home Remedies',
                'logged_in_as_patient': 'You are logged in as a',
                'explore_dashboard': 'Explore your dashboard and access health services',
                'chat_patients': 'Chat with Patients',
                'view_patient_records': 'View Patient Records',
                'view_all_users': 'View All Registered Users',
                'logged_in_as_doctor': 'You are logged in as a',
                'use_sidebar_navigate': 'Use the sidebar to navigate through your dashboard',
                'my_availability': 'My Availability',
                'availability': 'Availability',
                'ai_detection_description': '📷 Upload your skin photo and let our AI instantly analyze it with high accuracy.',
                'treatment_suggestions': 'Treatment Suggestions',
                'treatment_description': '👨‍⚕️ Get expert-backed treatment plans recommended by certified dermatologists.',
                'home_remedies_description': '🌿 Safe and natural home remedies for healthy skin.',
                'upload_your_image': 'Upload Your Image',
                'get_instant_ai_analysis': 'Get instant AI-powered skin analysis',
                'choose_image': 'Choose Image',
                'predict': 'Predict',
                'predicting': 'Predicting...',
                'prediction_result': 'Prediction Result',
                'please_select_image_first': 'Please select an image first',
                'our_services': 'Our Services',
                'skin_treatments': 'Skin Treatments',
                'acne_pimples_care': 'Acne & Pimples Care',
                'laser_therapy': 'Laser Therapy',
                'cosmetic_procedures': 'Cosmetic Procedures',
                'ai_disease_detection': 'AI Disease Detection',
                'our_expert_doctors': 'Our Expert Doctors',
                'dermatologist_exp': 'Dermatologist (5+ years exp.)',
                'cosmetic_specialist_exp': 'Cosmetic Specialist (25+ years exp.)',
                'laser_therapy_expert': 'Laser Therapy Expert',
                'how_our_ai_detection_works': 'How Our AI Detection Works',
                'upload_skin_image': 'Upload skin image',
                'ai_scans_image': 'AI scans the image',
                'get_disease_prediction': 'Get disease prediction',
                'consult_with_doctor': 'Consult with doctor',
                'patient_testimonials': 'Patient Testimonials',
                'great_experience_accurate': '"Great experience, AI detection was very accurate!"',
                'doctors_supportive_caring': '"Doctors are very supportive and caring."',
                'amazing_acne_results': '"Got treatment for acne, results were amazing!"',
                'frequently_asked_questions': 'Frequently Asked Questions',
                'is_ai_detection_accurate': 'Is AI detection accurate?',
                'ai_over_90_accuracy': 'Yes, our AI provides over 90% accuracy.',
                'do_i_still_need_doctor': 'Do I still need to see a doctor?',
                'ai_is_guide_consultation_important': 'Yes, AI is a guide, but final consultation is important.',
                'is_my_data_safe': 'Is my data safe?',
                'we_ensure_full_privacy': 'Yes, we ensure full privacy.',
                'our_services': 'Our Services',
                'skin_treatments': 'Skin Treatments',
                'acne_pimples_care': 'Acne & Pimples Care',
                'laser_therapy': 'Laser Therapy',
                'cosmetic_procedures': 'Cosmetic Procedures',
                'ai_disease_detection': 'AI Disease Detection',
                'our_expert_doctors': 'Our Expert Doctors',
                'dermatologist_exp': 'Dermatologist (5+ years exp.)',
                'cosmetic_specialist_exp': 'Cosmetic Specialist (25+ years exp.)',
                'laser_therapy_expert': 'Laser Therapy Expert',
                'how_our_ai_detection_works': 'How Our AI Detection Works',
                'upload_skin_image': 'Upload skin image',
                'ai_scans_image': 'AI scans the image',
                'get_disease_prediction': 'Get disease prediction',
                'consult_with_doctor': 'Consult with doctor',
                'patient_testimonials': 'Patient Testimonials',
                'great_experience_accurate': '"Great experience, AI detection was very accurate!"',
                'doctors_supportive_caring': '"Doctors are very supportive and caring."',
                'amazing_acne_results': '"Got treatment for acne, results were amazing!"',
                'frequently_asked_questions': 'Frequently Asked Questions',
                'is_ai_detection_accurate': 'Is AI detection accurate?',
                'ai_over_90_accuracy': 'Yes, our AI provides over 90% accuracy.',
                'do_i_still_need_doctor': 'Do I still need to see a doctor?',
                'ai_is_guide_consultation_important': 'Yes, AI is a guide, but final consultation is important.',
                'is_my_data_safe': 'Is my data safe?',
                'we_ensure_full_privacy': 'Yes, we ensure full privacy.',
                'no_appointments': 'No appointments',
                'complete': 'Complete',
                'reject': 'Reject',
                'completed': 'Completed',
                'rejected': 'Rejected',
                'error_loading_appointments': 'Error loading appointments. Please refresh.',
                'failed_to_complete_appointment': 'Failed to complete appointment',
                'enter_rejection_reason_optional': 'Enter rejection reason (optional):',
                'failed_to_reject_appointment': 'Failed to reject appointment',
                'edit_profile': 'Edit Profile',
                'specialization': 'Specialization',
                'update_profile': 'Update Profile',
                'back_to_dashboard': 'Back to Dashboard',
                'select_patient': 'Select a patient',
                'delete_chat': 'Delete Chat',
                'loading_patients': 'Loading patients...',
                'loading_chat': 'Loading chat',
                'type_message': 'Type a message',
                'send': 'Send',
                'registered_users': 'Registered Users',
                'all_registered_users': 'All Registered Users',
                'id': 'ID',
                'username': 'Username',
                'email': 'Email',
                'role': 'Role',
                'registered_at': 'Registered At',
                'action': 'Action',
                'confirm_delete_user': 'Are you sure you want to permanently delete this user?',
                'user_deleted_successfully': 'User deleted successfully',
                'delete_failed': 'Delete failed',
                'error_deleting_user': 'Error deleting user',
                                'server_error': 'Server error',
                'prediction_failed': 'Prediction failed',
                'prediction_error': 'Prediction Error',
                'disease': 'Disease',
                'confidence': 'Confidence',
                'risk_level': 'Risk Level',
                'reason': 'Reason',
                'symptoms': 'Symptoms',
                'prevention': 'Prevention',
                'low': 'Low',
                'na': 'N/A',
                'ask_chatbot': 'Ask AI Assistant',
                'chat_with_ai': 'Chat with AI',
                'ai_assistant': 'AI Assistant',
                'bot_response': 'Bot Response',
                'ask_ai': 'Ask AI',
                'ai_chat': 'AI Chat',
                'intelligent_chat': 'Intelligent Chat',
                'smart_assistant': 'Smart Assistant',
                'ai_help': 'AI Help',
                'get_ai_advice': 'Get AI Advice',
                'ai_consultation': 'AI Consultation',
                'ask_question': 'Ask Question',
                'type_your_question': 'Type your question',
                'ai_will_respond': 'AI will respond',
                'get_instant_answer': 'Get instant answer',
                'powered_by_ai': 'Powered by AI',
                'ai_medical_assistant': 'AI Medical Assistant',
                'healthcare_ai': 'Healthcare AI',
                'symptom_checker': 'Symptom Checker',
                'health_advice': 'Health Advice',
                'medical_ai_chat': 'Medical AI Chat',
                'ask_about_symptoms': 'Ask about symptoms',
                'ai_diagnosis_help': 'AI Diagnosis Help',
                'treatment_recommendation': 'Treatment Recommendation',
                'health_tips': 'Health Tips',
                'medical_guidance': 'Medical Guidance',
                'ai_healthcare': 'AI Healthcare',
                'ask_medical_question': 'Ask Medical Question',
                'get_expert_advice': 'Get Expert Advice',
                'ai_symptom_analysis': 'AI Symptom Analysis',
                'health_consultation': 'Health Consultation',
                'medical_chatbot': 'Medical Chatbot',
                'ask_about_treatment': 'Ask about treatment',
                'ai_medical_advice': 'AI Medical Advice',
                'healthcare_chat': 'Healthcare Chat',
                'ask_health_question': 'Ask Health Question',
                'get_ai_recommendation': 'Get AI Recommendation',
                'symptom_description': 'Symptom Description',
                'describe_your_symptoms': 'Describe your symptoms',
                'get_treatment_suggestions': 'Get treatment suggestions',
                'ai_health_assistant': 'AI Health Assistant',
                'medical_ai_consultation': 'Medical AI Consultation',
                'ask_about_health': 'Ask about health',
                'get_medical_advice': 'Get medical advice',
                'health_ai_chat': 'Health AI Chat',
                'ask_medical_ai': 'Ask Medical AI',
                'get_health_recommendations': 'Get health recommendations',
                'ai_medical_help': 'AI Medical Help',
                'healthcare_ai_assistant': 'Healthcare AI Assistant',
                'ask_about_disease': 'Ask about disease',
                'get_disease_info': 'Get disease information',
                'ai_disease_detection': 'AI Disease Detection',
                'medical_ai_chatbot': 'Medical AI Chatbot',
                'ask_about_medical_condition': 'Ask about medical condition',
                'get_condition_info': 'Get condition information',
                'ai_medical_diagnosis': 'AI Medical Diagnosis',
                'healthcare_ai_chat': 'Healthcare AI Chat',
                'ask_about_health_issue': 'Ask about health issue',
                'get_health_issue_info': 'Get health issue information',
                'ai_health_diagnosis': 'AI Health Diagnosis',
                'medical_ai_assistant': 'Medical AI Assistant',
                'healthcare_ai_consultation': 'Healthcare AI Consultation',
                'ask_about_medical_problem': 'Ask about medical problem',
                'get_medical_problem_info': 'Get medical problem information',
                'ai_medical_analysis': 'AI Medical Analysis',
                'healthcare_ai_diagnosis': 'Healthcare AI Diagnosis',
                'medical_ai_help': 'Medical AI Help',
                'healthcare_ai_assistant': 'Healthcare AI Assistant'
            },
            'hi': {
                'skin_disease_detection': 'त्वचा रोग पहचान',
                'login': 'लॉगिन',
                'register': 'रजिस्टर करें',
                'dashboard': 'डैशबोर्ड',
                'contact': 'संपर्क करें',
                'chat': 'चैट',
                'upload': 'अपलोड',
                'about': 'हमारे बारे में',
                'about_description': 'Snehdip SkinCare एक AI संचालित वेब प्लेटफ़ॉर्म है जो त्वचा रोगों का जल्द पता लगाने के लिए डिज़ाइन किया गया है। चिकित्सा डेटासेट पर प्रशिक्षित उन्नत गहरे शिक्षण मॉडल के साथ, हम त्वरित रोग भविष्यवाणियां, उपचार मार्गदर्शन और अस्पताल की जानकारी प्रदान करते हैं - घर से स्वास्थ्य सेवा तक पहुंच प्रदान करते हैं।',
                'home': 'होम',
                'username': 'वापरकर्ता नाव',
                'email': 'ईमेल',
                'password': 'पासवर्ड',
                'submit': 'सबमिट करा',
                'cancel': 'रद्द करा',
                'book_appointment': 'भेटी नियुक्त करा',
                'doctor': 'डॉक्टर',
                'patient': 'रुग्ण',
                'select_doctor': 'डॉक्टर चुनें',
                'select_date': 'तिथि चुनें',
                'select_time': 'समय चुनें',
                'describe_issue': 'अपनी स्वास्थ्य समस्या बताएं',
                'welcome': 'स्वागत है',
                'logout': 'लॉगआउट',
                'profile': 'प्रोफ़ाइल',
                'settings': 'सेटिंग्स',
                'services': 'सेवाएं',
                'diagnosis_result': 'निदान परिणाम',
                'upload_description': 'Upload your skin image in seconds and get:',
                'instant_ai_prediction': 'Instant AI prediction',
                'probability_score': 'Probability score',
                'treatment_guidance': 'Treatment guidance',
                'save_reports': 'Save reports',
                'access_verified_hospital': 'Access verified hospital and dermatologist info:',
                'nearby_hospitals': 'Nearby hospitals',
                'dermatologist_list': 'Dermatologist list',
                'emergency_contacts': 'Emergency contacts',
                'appointment_guidance': 'Appointment guidance',
                'confidence': 'विश्वास',
                'risk_level': 'जोखिम स्तर',
                'symptoms': 'लक्षण',
                'prevention': 'रोकथाम',
                'treatment': 'इलाज',
                'upload_image': 'चित्र अपलोड करें',
                'choose_file': 'फाइल चुनें',
                'analyze': 'विश्लेषण करें',
                'loading': 'लोड हो रहा है...',
                'error': 'त्रुटि',
                'success': 'सफलता',
                'warning': 'चेतावनी',
                'please_wait': 'कृपया प्रतीक्षा करें...',
                'processing': 'प्रसंस्करण हो रहा है...',
                'results_ready': 'परिणाम तैयार हैं',
                'no_results': 'कोई परिणाम नहीं मिले',
                'try_again': 'फिर से कोशिश करें',
                'appointment_booked': 'अपॉइंटमेंट सफलतापूर्वक बुक हो गई!',
                'appointment_failed': 'अपॉइंटमेंट बुक करने में असफल',
                'invalid_credentials': 'अमान्य क्रेडेंशियल',
                'user_exists': 'उपयोगकर्ता पहले से मौजूद है',
                'registration_success': 'पंजीकरण सफल!',
                'login_success': 'लॉगिन सफल!',
                'logout_success': 'सफलतापूर्वक लॉग आउट!',
                'select_language': 'भाषा चुनें',
                'english': 'English',
                'hindi': 'हिंदी',
                'marathi': 'मराठी',
                'get_started': 'शुरू करें',
                'ai_detection': 'AI रोग पहचान',
                'home_remedies': 'घरेलू उपचार',
                'video_consultation': 'वीडियो परामर्श',
                'appointment_booking': 'अपॉइंटमेंट बुकिंग',
                'hospital': 'अस्पताल',
                'hospitals': 'अस्पताल',
                'online_consultation': 'ऑनलाइन परामर्श',
                'contact_doctor': 'डॉक्टर से संपर्क करें',
                'chat_with_bot': 'AI सहायक के साथ चैट करें',
                'please_log_in': 'जारी रखने के लिए कृपया लॉग इन करें',
                'enter_email': 'अपना ईमेल दर्ज करें',
                'enter_password': 'अपना पासवर्ड दर्ज करें',
                'dont_have_account': 'क्या आपके पास खाता नहीं है?',
                'register_here': 'यहां रजिस्टर करें',
                'create_account': 'अपना खाता बनाएं',
                'role': 'भूमिका',
                'select_role': 'भूमिका चुनें',
                'enter_username': 'उपयोगकर्ता नाम दर्ज करें',
                'enter_name': 'नाम दर्ज करें',
                'enter_email': 'ईमेल दर्ज करें',
                'select_doctor': 'डॉक्टर चुनें',
                'select_date_first': '-- पहले तिथि चुनें --',
                'book_appointment_description': 'हमारे विशेषज्ञ त्वचा विशेषज्ञों के साथ परामर्श करें',
                'chat_doctor': 'डॉक्टर से चैट करें',
                'my_appointments': 'मेरी अपॉइंटमेंट्स',
                'upload_skin_image': 'त्वचा छवि अपलोड करें',
                'find_hospitals': 'अस्पताल खोजें',
                'buy_medicines': 'दवाएं खरीदें',
                'open_records': 'अपने रिकॉर्ड खोलें',
                'my_records': 'मेरे रिकॉर्ड',
                'appointment_queue': 'अपॉइंटमेंट क्यू',
                'home_remedies': 'घरेलू उपचार',
                'logged_in_as_patient': 'आप एक के रूप में लॉग इन हैं',
                'explore_dashboard': 'अपना डैशबोर्ड एक्सप्लोर करें और स्वास्थ्य सेवाओं तक पहुंचें',
                'chat_patients': 'रोगियों से चैट करें',
                'view_patient_records': 'रोगी रिकॉर्ड देखें',
                'view_all_users': 'सभी पंजीकृत उपयोगकर्ताओं को देखें',
                'logged_in_as_doctor': 'आप एक के रूप में लॉग इन हैं',
                'use_sidebar_navigate': 'अपने डैशबोर्ड के माध्यम से नेविगेट करने के लिए साइडबार का उपयोग करें',
                'my_availability': 'मेरी उपलब्धता',
                'availability': 'उपलब्धता',
                'ai_detection_description': '📷 अपनी त्वचा की फोटो अपलोड करें और हमारे AI को तुरंत उच्च सटीकता के साथ विश्लेषण करने दें।',
                'treatment_suggestions': 'उपचार सुझाव',
                'treatment_description': '👨‍⚕️ प्रमाणित त्वचा विशेषज्ञों द्वारा अनुशंसित विशेषज्ञ-समर्थित उपचार योजनाएं प्राप्त करें।',
                'home_remedies_description': '🌿 स्वस्थ त्वचा के लिए सुरक्षित और प्राकृतिक घरेलू उपचार।',
                'welcome_to_snehdip_skincare_hospital': 'स्नेहदीप स्किनकेयर अस्पताल में आपका स्वागत है',
                'hospitals_services_description': 'त्वचा उपचार, त्वचा विशेषज्ञ, सौंदर्य प्रक्रियाएं, मुंहास उपचार, लेजर थेरेपी, त्वचा सलाह।',
                'snehdip_skincare_is_dedicated_to_providing_the_best_dermatological_services_with_a_focus_on_modern_treatments_patient_comfort_and_professional_care': 'स्नेहदीप स्किनकेयर आधुनिक उपचार, रोगी की देखभाल और पेशेवर देखभाल पर ध्यान केंद्रित करके सर्वोत्तम त्वचा विशेषज्ञ सेवाएं प्रदान करने के लिए समर्पित है।'
            },
            'mr': {
                'skin_disease_detection': 'त्वचेचा आजार ओळख',
                'login': 'लॉगिन',
                'register': 'नोंदणी करा',
                'dashboard': 'डॅशबोर्ड',
                'contact': 'संपर्क',
                'chat': 'गपशप',
                'upload': 'अपलोड',
                'about': 'आमच्याबद्दल',
                'about_description': 'स्नेहदीप स्किनकेयर हे एक AI संचालित वेब प्लॅटफॉर्म आहे जो त्वचेच्या आजारांचा जल्द पता लगान्यासाठी डिझाइन केलेला आहे. चिकित्सा डेटासेटवर प्रशिक्षित उन्नत गहरे शिक्षण मॉडलसह, आम्ही त्वचेच्या आजारांचा अंदाज, उपचार मार्गदर्शन आणि रुग्णालयाची माहिती प्रदान करतो - घरातून आरोग्य सेवा प्रदान करतो.',
                'login_register': 'लॉगिन आणि नोंदणी करा',
                'create_secure_account': 'सर्वर खातरी खाते तयार करा आणि सर्व AI वैशठतांमध्ये प्रवेश करा.',
                'quick_simple_registration': 'जलद आणि सोपे नोंदणी करा',
                'encrypted_secure_login': 'एनक्रिप्टेड सुरक्षित लॉगिन',
                'personalized_dashboard': 'वैयक्षकृती डॅशबोर्ड',
                'save_track_reports': 'अहेवे ठेवत आणि अहवाल करा',
                'upload_description': 'सेकंडात तुमची त्वचेची फोटो अपलोड करा आणि मिळवा मिळवा:',
                'instant_ai_prediction': 'त्वरंत AI भविषित',
                'probability_score': 'संभावनाता गुण',
                'treatment_guidance': 'उपचार मार्गदर्शन',
                'save_reports': 'अहेवे ठेवत आणि अहवाल करा',
                'access_verified_hospital': 'सत्यापित रुग्णालय आणि त्वचा तज्ञांची माहिती मिळवा:',
                'nearby_hospitals': 'जवळीच्या रुग्णालय',
                'dermatologist_list': 'त्वचा तज्ञांची यादी',
                'emergency_contacts': 'आपातकाळी संपर्क',
                'appointment_guidance': 'भेटी नियुक्त मार्गदर्शन',
                'home': 'होम',
                'username': 'वापरकर्ता नाव',
                'email': 'ईमेल',
                'password': 'पासवर्ड',
                'submit': 'सबमिट करा',
                'cancel': 'रद्द करा',
                'book_appointment': 'भेटी नियुक्त करा',
                'doctor': 'डॉक्टर',
                'patient': 'रुग्ण',
                'select_doctor': 'डॉक्टर निवडा',
                'home': 'होम',
                'username': 'वापरकर्ता नाव',
                'email': 'ईमेल',
                'password': 'पासवर्ड',
                'submit': 'सबमिट करा',
                'cancel': 'रद्द करा',
                'book_appointment': 'भेटी नियुक्त करा',
                'doctor': 'डॉक्टर',
                'patient': 'रुग्ण',
                'select_doctor': 'डॉक्टर निवडा',
                'select_date': 'तारीख निवडा',
                'select_time': 'वेळ निवडा',
                'describe_issue': 'आपली आरोग्य समस्या सांगा',
                'welcome': 'स्वागत',
                'logout': 'बाहेर पडा',
                'profile': 'प्रोफाइल',
                'settings': 'सेटिंग्ज',
                'edit_profile': 'प्रोफाइल संपादित करा',
                'specialization': 'विशेषज्ञता',
                'update_profile': 'प्रोफाइल अपडेट करा',
                'back_to_dashboard': 'डॅशबोर्डवर परत जा',
                'select_patient': 'रुग्ण निवडा',
                'delete_chat': 'चॅट हटवा',
                'loading_patients': 'रुग्ण लोड होत आहेत...',
                'loading_chat': 'चॅट लोड होत आहे...',
                'type_message': 'संदेश टाइप करा',
                'send': 'पाठवा',
                'registered_users': 'नोंदणीकृत वापरकर्ते',
                'all_registered_users': 'सर्व नोंदणीकृत वापरकर्ते',
                'id': 'आयडी',
                'username': 'वापरकर्ता नाव',
                'email': 'ईमेल',
                'role': 'भूमिका',
                'registered_at': 'नोंदणीकृत',
                'action': 'कृती',
                'confirm_delete_user': 'तुम्हाला खात्री आहे की तुम्ही हा वापरकर्ता कायमचा हटवू इच्छिता?',
                'user_deleted_successfully': 'वापरकर्ता यशस्वीरित्या हटवला',
                'delete_failed': 'हटवणे अयशस्वी',
                'error_deleting_user': 'वापरकर्ता हटवण्यात त्रुटी',
                'settings': 'सेटिंग्ज',
                'services': 'सेवा',
                'diagnosis_result': 'निदान परिणाम',
                'confidence': 'विश्वास',
                'risk_level': 'धोकाम स्तर',
                'symptoms': 'लक्षणे',
                'prevention': 'प्रतिबंध',
                'treatment': 'उपचार',
                'upload_image': 'फोटो अपलोड करा',
                'choose_file': 'फाइल निवडा',
                'analyze': 'विश्लेषण करा',
                'loading': 'लोड होत आहे...',
                'error': 'त्रुटी',
                'success': 'यशस्वी',
                'warning': 'खबरदारी',
                'please_wait': 'कृपया थांबा...',
                'processing': 'प्रक्रिया सुरू आहे...',
                'results_ready': 'परिणाम तयार आहेत',
                'no_results': 'कोणतेही परिणाम सापडले नाहीत',
                'try_again': 'पुन्हा प्रयत्न करा',
                'appointment_booked': 'भेटी यशस्वीरित्या नियुक्त झाली!',
                'appointment_failed': 'भेटी नियुक्त करण्यात अयशस्वी',
                'invalid_credentials': 'अवैध क्रेडेन्शियल्स',
                'user_exists': 'वापरकर्ता आधीच अस्तित्वात आहे',
                'registration_success': 'नोंदणी यशस्वी!',
                'login_success': 'लॉगिन यशस्वी!',
                'logout_success': 'यशस्वीरित्या लॉग आउट!',
                'select_language': 'भाषा निवडा',
                'english': 'English',
                'hindi': 'हिंदी',
                'marathi': 'मराठी',
                'get_started': 'सुरू करा',
                'ai_detection': 'AI त्वचेचा आजार ओळख',
                'home_remedies': 'घरी उपचार',
                'video_consultation': 'व्हिडिओ ऑनलाईन',
                'appointment_booking': 'भेटी बुकिंग',
                'hospital': 'रुग्णालय',
                'hospitals': 'रुग्णालये',
                'welcome_to_snehdip_skincare_hospital': 'स्नेहदीप स्किनकेयर रुग्णालयात आपले स्वागत',
                'hospitals_services_description': 'त्वचा उपचार, त्वचाविज्ञान, सौंदर्य प्रक्रिया, मुंहास उपचार, लेजर थेरपी, त्वचा सल्ला.',
                'snehdip_skincare_is_dedicated_to_providing_the_best_dermatological_services_with_a_focus_on_modern_treatments_patient_comfort_and_professional_care': 'स्नेहदीप स्किनकेयर आधुनिक उपचार, रुग्ण सोय आणि व्यावसायिक देखभाल यावर लक्ष केंद्रित करून सर्वोत्तम त्वचाविज्ञान सेवा प्रदान करण्यासाठी समर्पित आहे.',
                'online_consultation': 'ऑनलाइन सल्ला',
                'contact_doctor': 'डॉक्टरशी संपर्क साधा',
                'chat_with_bot': 'AI सहाय्यकाराशी गपशप करा',
                'please_log_in': 'सुरू ठेवण्यासाठी कृपया लॉग इन करा',
                'enter_email': 'आपला ईमेल नमूद करा',
                'enter_password': 'आपला पासवर्ड नमूद करा',
                'dont_have_account': 'आपल्याजवळ खाते नाही का?',
                'register_here': 'येथे नोंदणी करा',
                'create_account': 'आपले खाते तयार करा',
                'role': 'भूमिका',
                'select_role': 'भूमिका निवडा',
                'enter_username': 'आपले वापरकर्ता नाव नमूद करा',
                'enter_name': 'नाव नमूद करा',
                'enter_email': 'ईमेल नमूद करा',
                'select_doctor': 'डॉक्टर निवडा',
                'select_date_first': '-- प्रथम तारीख निवडा --',
                'book_appointment_description': 'आमच्या तज्ञ त्वचाविज्ञांशी परामर्श करा',
                'already_have_account': 'आपल्याजवळ आधीच खाते आहेत का?',
                'login_here': 'येथे लॉग इन करा',
                'chat_doctor': 'डॉक्टरशी गपशप करा',
                'my_appointments': 'माझे भेटी नियुक्ती',
                'upload_skin_image': 'त्वचेचा प्रतिमा अपलोड करा',
                'find_hospitals': 'रुग्णालय शोधा',
                'buy_medicines': 'औषधे खरेदी करा',
                'open_records': 'आपले रेकॉर्ड उघडा',
                'my_records': 'माझे रेकॉर्ड',
                'appointment_queue': 'भेटी रांग',
                'home_remedies': 'घरी उपचार',
                'logged_in_as_patient': 'आप एक म्हणून लॉग इन आहात',
                'explore_dashboard': 'आपला डॅशबोर्ड एक्सप्लोर करा आणि आरोग्य सेवांमध्ये प्रवेश करा',
                'chat_patients': 'रुग्णांशी गपशप करा',
                'view_patient_records': 'रुग्णांचे रेकॉर्ड पहा',
                'view_all_users': 'सर्व नोंदणीकृत वापरकर्ते पहा',
                'logged_in_as_doctor': 'आप एक म्हणून लॉग इन आहात',
                'use_sidebar_navigate': 'आपल्या डॅशबोर्डमध्ये नेविगेट करण्यासाठी साइडबार वापरा',
                'my_availability': 'माझी उपलब्धता',
                'availability': 'उपलब्धता',
                'ai_detection_description': '📷 आपली त्वचेची फोटो अपलोड करा आणि आमच्या AIला त्वरित उच्च अचूकतेसह विश्लेषण करून घ्या.',
                'treatment_suggestions': 'उपचार सूचना',
                'treatment_description': '👨‍⚕️ प्रमाणित त्वचा तज्ञांनी शिफारस केलेले तज्ञ-समर्थित उपचार योजना मिळवा.',
                'home_remedies_description': '🌿 निरोगी त्वचेसाठी सुरक्षित आणि नैसर्गिक घरी उपाय.'
            }
        }
    
    def get_current_language(self):
        """Get current language from session or default to English"""
        return session.get('lang', self.default_lang)
    
    def translate_text(self, text, lang=None):
        """Translate text to current language with caching"""
        # Use provided lang or get from session
        if lang is None:
            lang = self.get_current_language()
        
        # Check predefined translations first (including English)
        if text in self.translations.get(lang, {}):
            return self.translations[lang][text]
        
        # If target is English and no predefined translation, return original text
        if lang == 'en':
            return text
        
        # Use API translation for non-predefined text
        try:
            translator = GoogleTranslator(source='en', target=lang)
            translated = translator.translate(text)
            return translated
        except Exception as e:
            print(f"Translation error: {e}")
            return text  # Return original on error

# Global translator instance
translator_instance = MultiLanguageTranslator()

def translate_text(text, lang=None):
    """Global translation function that uses session language"""
    return translator_instance.translate_text(text, lang)